### ISSUE TITLE
Transfer Ownership

### ISSUE THREAD

**Issue by hishamco** [OrchardCoreContrib/PoExtractor#60]
Hi @lukaskabrt, first of all I appeciate all the efforts on PoExtractor which of course helps OC, lately I notice there are some issue and PR pending without any action, so if you are busy or not able to maintain the repo please transfer the owner ship to me as part of Orchard Core Contrib, the  I will keep continue to work on this. Last time we mentioned the might be add to OC organization, but while no action has been made yet, I will take the initiative, then if we decide later to move it to OC I will do

Hope you understand the situation, because we need to fix all the issue to continue work with what you started, thanks again

**Comment by rjpowers10** [comment]
I'm hoping this gets transferred somewhere soon. I tried using the tool today and it won't run without .NET Core 3.0 installed, which has long been out of support.

**Comment by hishamco** [comment]
Hope to get answer from Lukas ASAP, otherwise I might need to create a fork, then start

**Comment by lukaskabrt** [comment]
@hishamco I have tried to transfer the repo ownership to OrcharCoreContrib, but the operation failed with the error

> You don’t have the permission to create public repositories on OrchardCoreContrib  

Can you grant me (temporarily) permission to create public repositories on OrchardCoreContrib?

**Comment by hishamco** [comment]
Hi Lukas, I will give you a permission now ..

**Comment by hishamco** [comment]
@lukaskabrt I just send you an invitation, please accept it and I will set a proper permission for you

**Comment by lukaskabrt** [comment]
Done. The repository transfer is in progress.

@hishamco can you send me your email address, so I can add you as a package owner on Nuget?

**Comment by hishamco** [comment]
hishamco_2007@hotmail.com

**Comment by hishamco** [comment]
We might change the package name later on to something like `OrchardCoreContrib.PoExtrator`

**Comment by hishamco** [comment]
@rjpowers10 the repo is moved to OCC, so please feel free to open any issue there, thanks @lukaskabrt for your collaboration, now you are a member of OCC, feel free to add any contribution if you have a time, for now I will take care about the current issues and PRs

Thanks

**Comment by lukaskabrt** [comment]
Thank for taking care of the project.

You should receive invitation to manage PoExtractor and PoExtractor.OrchardCore NuGet packages, also I have added you to DevOps project https://dev.azure.com/kabrt/PoExtractor, where CI/CD pipelines are setup. I am not sure if there is an easy way to transfer DevOps project, but if you would like to continue using Azure DevOps I will have a look.

**Comment by hishamco** [comment]
May be I will use the same AzurePipeline that I'm currently using for other repos, I will start working on this today

**Comment by lukaskabrt** [comment]
OK, if you need anything else let me know.

**Comment by hishamco** [comment]
One more thing, did you remember that OC issue no. that we are dicussed the transfer process?

**Comment by lukaskabrt** [comment]
https://github.com/OrchardCMS/OrchardCore/discussions/12612

**Comment by hishamco** [comment]
@lukaskabrt I just release a preview version after I did some enhancements and bug fixing https://github.com/OrchardCoreContrib/OrchardCoreContrib.PoExtractor/releases/tag/v1.0.0-preview

One thing I need to mention can I add a section in `README.md` titled "CREDITS" mentioing you as the original author or do you have a better idea

**Comment by lukaskabrt** [comment]
I think "credits" section is fine. Than you.

**Comment by hishamco** [comment]
FYI https://github.com/OrchardCoreContrib/OrchardCoreContrib.PoExtractor#credits
